### ISSUE TITLE
Issue with astropy-healpix when installing using pip

### ISSUE THREAD

**Issue by shashankdholakia** [astropy/astropy-healpix#78] opened 2018-04-30 01:46 UTC
Getting an error when attempting to use the astropy affiliated reproject package using pip in an Anaconda environment (pasted full traceback pasted here):
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/shashank/anaconda2/envs/iraf27/lib/python2.7/site-packages/reproject/__init__.py", line 15, in <module>
    from .healpix import reproject_from_healpix, reproject_to_healpix
  File "/Users/shashank/anaconda2/envs/iraf27/lib/python2.7/site-packages/reproject/healpix/__init__.py", line 1, in <module>
    from .high_level import *
  File "/Users/shashank/anaconda2/envs/iraf27/lib/python2.7/site-packages/reproject/healpix/high_level.py", line 1, in <module>
    from .core import healpix_to_image, image_to_healpix
  File "/Users/shashank/anaconda2/envs/iraf27/lib/python2.7/site-packages/reproject/healpix/core.py", line 7, in <module>
    from astropy_healpix import npix_to_nside, HEALPix
  File "/Users/shashank/anaconda2/envs/iraf27/lib/python2.7/site-packages/astropy_healpix/__init__.py", line 13, in <module>
    from .high_level import *  # noqa
  File "/Users/shashank/anaconda2/envs/iraf27/lib/python2.7/site-packages/astropy_healpix/high_level.py", line 9, in <module>
    from .core import (nside_to_pixel_area, nside_to_pixel_resolution,
  File "/Users/shashank/anaconda2/envs/iraf27/lib/python2.7/site-packages/astropy_healpix/core.py", line 12, in <module>
    from . import core_cython
ImportError: dlopen(/Users/shashank/anaconda2/envs/iraf27/lib/python2.7/site-packages/astropy_healpix/core_cython.so, 2): Symbol not found: _GOMP_parallel
  Referenced from: /Users/shashank/anaconda2/envs/iraf27/lib/python2.7/site-packages/astropy_healpix/core_cython.so
  Expected in: flat namespace
 in /Users/shashank/anaconda2/envs/iraf27/lib/python2.7/site-packages/astropy_healpix/core_cython.so
```
Fixed the issue by uninstalling astropy-healpix and reinstalling it from the conda-forge channel. Seems to be a gcc linking issue?

**Comment by cdeil** [comment] 2018-04-30 07:01
@shashankdholakia - Yes, there was an OpenMP-related linking issue (see the mention of `dlopen` and `_GOMP_parallel` in your traceback).

So you updated your install and now have a working version?

If yes, I think we could either close this issue, or alternatively, if we want to try and pin down the issue, you'd have to give us more information, specifically with which version of astropy-healpix, and installed how, to reproduce the issue.

**Comment by shashankdholakia** [comment] 2018-04-30 08:03
I am using astropy-healpix version 0.2.0 on python 2.7.14. Pip automatically installed the package as a dependency, but when it did not work, I uninstalled and reinstalled the package again using pip with no success.

I now have a working version from the conda-forge channel, yes.

**Comment by cdeil** [comment] 2018-04-30 08:16
I tried this on my Mac just now:
```
conda create --name hpx-issue python=2.7 astropy
source activate hpx-issue
pip install astropy-healpix
python -c 'import astropy_healpix'
```

It does not give the error you report, i.e. the install and import works fine.

@shashankdholakia - could you please try these commands and see if they reproduce the error? And if no, try to give us commands to reproduce the error?

@astrofrog - Do you have any thoughts on how to reproduce this issue? Are there any commands we can run to check the relevant compiler / OpenMP info to try and pin down this issue? We definitely want the install to work with pip also, right?

**Comment by astrofrog** [comment] 2018-04-30 08:56
I think this must indicate some issue in the code that determines whether OpenMP flags can be used. I'll investigate!

**Comment by astrofrog** [comment] 2018-04-30 10:49
@shashankdholakia - can you let me know the output of:

```
conda list
```

Thanks!

**Comment by shashankdholakia** [comment] 2018-04-30 19:02
I have two separate environments on my Mac, both with python 2.7.14 and am able to reproduce the issue on both of them if I 'pip install astropy-healpix'

Here is the full output of conda list in one of the environments. 

# packages in environment at /Users/shashank/anaconda2/envs/iraf27:
#
acor                      1.1.1                     <pip>
acstools                  2.0.9                    py27_0    http://ssb.stsci.edu/astroconda
alabaster                 0.7.10           py27h9dd7d6e_0  
appdirs                   1.4.0                    py27_0    http://ssb.stsci.edu/astroconda
appnope                   0.1.0            py27hb466136_0  
asdf                      1.3.1                    py27_2    http://ssb.stsci.edu/astroconda
asn1crypto                0.22.0           py27h61af4a7_1  
astroimtools              0.1.1                    py27_1    http://ssb.stsci.edu/astroconda
astropy                   2.0.2            py27h87cc2bd_4  
astropy-healpix           0.2                      py27_0    conda-forge
autograd                  1.2                       <pip>
babel                     2.5.0            py27h7311c9e_0  
backports                 1.0              py27hb4f9756_1  
backports.functools_lru_cache 1.4              py27h2aca819_1  
backports.shutil_get_terminal_size 1.0.0            py27hc9115de_2  
backports_abc             0.5              py27h6972548_0  
batman-package            2.4.6                     <pip>
beautifulsoup4            4.6.0                     <pip>
bleach                    2.0.0            py27ha7d1710_0  
bokeh                     0.12.10          py27hf91827b_0  
bs4                       0.0.1                     <pip>
ca-certificates           2018.4.16                     0    conda-forge
calcos                    3.2.1                    py27_0    http://ssb.stsci.edu/astroconda
certifi                   2018.4.16                py27_0    conda-forge
cffi                      1.10.0           py27haac214c_1  
cfitsio                   3.370                         1    http://ssb.stsci.edu/astroconda
chardet                   3.0.4            py27h2842e91_1  
click                     6.7              py27h2b86a94_0  
cloudpickle               0.5.2            py27he962bb2_0  
configobj                 5.0.6                     <pip>
configparser              3.5.0            py27hc7edf1b_0  
corner                    2.0.1                     <pip>
costools                  1.2.1                    py27_1    http://ssb.stsci.edu/astroconda
crds                      7.1.5                    py27_0    http://ssb.stsci.edu/astroconda
cryptography              2.0.3            py27hab69567_1  
cycler                    0.10.0           py27hfc73c78_0  
cython                    0.26.1           py27h6a053f9_0  
d2to1                     0.2.12                   py27_0    http://ssb.stsci.edu/astroconda
dask                      0.16.0           py27h0cfea73_0  
dask-core                 0.16.0           py27h3e6bc05_0  
dbus                      1.10.22              h50d9ad6_0  
decorator                 4.0.9                    py27_0    http://ssb.stsci.edu/astroconda
dill                      0.2.7.1          py27hc0d316d_0  
distributed               1.20.0           py27h9e4a8dc_0  
docopt                    0.6.2                    py27_0  
docutils                  0.14             py27h0befae3_0  
drizzlepac                2.1.20                   py27_0    http://ssb.stsci.edu/astroconda
ds9                       7.5                           0    http://ssb.stsci.edu/astroconda
emcee                     2.2.1                     <pip>
entrypoints               0.2.3            py27hd680fb1_2  
enum34                    1.1.6            py27hf475452_1  
expat                     2.2.5                hb8e80ba_0  
fftw                      3.3.4                         0    http://ssb.stsci.edu/astroconda
fitsblender               0.3.2                    py27_0    http://ssb.stsci.edu/astroconda
fitsverify                4.18                          1    http://ssb.stsci.edu/astroconda
freetype                  2.8                  h12048fb_1  
funcsigs                  1.0.2                     <pip>
functools32               3.2.3.2          py27h8ceab06_1  
future                    0.16.0                   py27_1  
futures                   3.1.1            py27hb02a37a_0  
gettext                   0.19.8.1             h15daf44_3  
ginga                     2.6.6                    py27_0    http://ssb.stsci.edu/astroconda
glib                      2.53.6               h33f6a65_2  
glue-core                 0.12.0                   py27_0    http://ssb.stsci.edu/astroconda
glue-ginga                0.2                      py27_0    http://ssb.stsci.edu/astroconda
glue-vispy-viewers        0.9                      py27_0    http://ssb.stsci.edu/astroconda
glueviz                   0.12.0                        0    http://ssb.stsci.edu/astroconda
gsl                       2.2.1                h002c638_3  
h5py                      2.7.1            py27h75626f5_0  
hdf5                      1.10.1               ha036c08_1  
heapdict                  1.0.0            py27hb5e74ad_0  
hstcal                    1.3.0                         0    http://ssb.stsci.edu/astroconda
htc_utils                 0.1                      py27_0    http://ssb.stsci.edu/astroconda
html5lib                  0.999999999      py27hec7e2bc_0  
icu                       58.2                 h4b95b61_1  
idna                      2.6              py27hedea723_1  
imageio                   2.2.0            py27h37746d9_0  
imagesize                 0.7.1            py27h4f7bcc8_0  
imexam                    0.8.0                    py27_0    http://ssb.stsci.edu/astroconda
intel-openmp              2018.0.0             h8158457_8  
ipaddress                 1.0.18           py27h5b9a5b9_0  
ipykernel                 4.6.1            py27h1e70a78_0  
ipython                   5.4.1            py27h2b3d779_1  
ipython_genutils          0.2.0            py27h8b9a179_0  
iraf                      2.16.UR                       1    http://ssb.stsci.edu/astroconda
iraf-all                  1.0                           1    http://ssb.stsci.edu/astroconda
iraf-x11                  2.0                           1    http://ssb.stsci.edu/astroconda
iraf.adccdrom             2013_01_02                    1    http://ssb.stsci.edu/astroconda
iraf.axe                  2.5                           2    http://ssb.stsci.edu/astroconda
iraf.cfh12k               2013_01_02                    1    http://ssb.stsci.edu/astroconda
iraf.cirred               2007_12_13                    1    http://ssb.stsci.edu/astroconda
iraf.ctio                 2010_11_18                    1    http://ssb.stsci.edu/astroconda
iraf.cutoutpkg            2001_04_05                    1    http://ssb.stsci.edu/astroconda
iraf.deitab               2013_01_02                    1    http://ssb.stsci.edu/astroconda
iraf.esowfi               2013_01_02                    1    http://ssb.stsci.edu/astroconda
iraf.finder               2.2                           1    http://ssb.stsci.edu/astroconda
iraf.fitsutil             2011_02_22                    1    http://ssb.stsci.edu/astroconda
iraf.gemini               1.14                          0    http://ssb.stsci.edu/astroconda
iraf.gmisc                2010_11_18                    1    http://ssb.stsci.edu/astroconda
iraf.guiapps              2010_11_18                    1    http://ssb.stsci.edu/astroconda
iraf.mem0                 2013_01_02                    1    http://ssb.stsci.edu/astroconda
iraf.mscdb                2011_02_28                    1    http://ssb.stsci.edu/astroconda
iraf.mscred               5.04                          1    http://ssb.stsci.edu/astroconda
iraf.mtools               2013_01_02                    1    http://ssb.stsci.edu/astroconda
iraf.nfextern             2013_01_02                    1    http://ssb.stsci.edu/astroconda
iraf.rvsao                2.7.8                         1    http://ssb.stsci.edu/astroconda
iraf.sqiid                2013_01_02                    1    http://ssb.stsci.edu/astroconda
iraf.stecf                3.17                          1    http://ssb.stsci.edu/astroconda
iraf.stsdas               3.17                          1    http://ssb.stsci.edu/astroconda
iraf.tables               3.17                          1    http://ssb.stsci.edu/astroconda
iraf.ucsclris             2013_01_02                    1    http://ssb.stsci.edu/astroconda
iraf.upsqiid              2013_01_02                    1    http://ssb.stsci.edu/astroconda
iraf.xdimsum              2010_11_18                    1    http://ssb.stsci.edu/astroconda
iraf.xray                 2.5.y2k                       1    http://ssb.stsci.edu/astroconda
isochrones                0.9.1                     <pip>
jinja2                    2.9.6            py27h92590e2_1  
jpeg                      9b                   he5867d9_2  
jsonschema                2.6.0            py27hd9b497e_0  
jupyter_client            5.1.0            py27hfaf569a_0  
jupyter_core              4.4.0            py27h5ea6ba4_0  
K2ephem                   1.5.0                     <pip>
k2flix                    2.3.0                     <pip>
K2fov                     7.1.1                     <pip>
k2mosaic                  2.0.0                     <pip>
libcxx                    4.0.1                h579ed51_0  
libcxxabi                 4.0.1                hebd6815_0  
libedit                   3.1                  hb4e282d_0  
libffi                    3.2.1                h475c297_4  
libgcc                    4.8.5               hdbeacc1_10  
libgfortran               3.0.1                h93005f0_2  
libiconv                  1.15                 hdd342a3_7  
libpng                    1.6.32               hd1e8b91_4  
libsodium                 1.0.15               hd9e47c5_0  
libtiff                   4.0.9                h0dac147_0  
libxml2                   2.9.4                hf05c021_6  
libxslt                   1.1.29               hc208041_6  
lightkurve                1.0.0.dev0                <pip>
llvmlite                  0.21.0                    <pip>
locket                    0.2.0            py27ha10513d_1  
lockfile                  0.12.2                   py27_0  
lxml                      4.1.0            py27hcb5f3a6_0  
markupsafe                1.0              py27hd3c86fa_1  
matplotlib                2.1.2                     <pip>
matplotlib                2.1.0            py27h3078195_0  
mdp                       3.5                      py27_0  
mistune                   0.8.1            py27hd7d4354_0  
mkl                       2018.0.1             hfbd8650_4  
mpi4py                    3.0.0                     <pip>
msgpack-python            0.4.8            py27h635ded4_0  
nbconvert                 5.3.1            py27h6455e4c_0  
nbformat                  4.4.0            py27hddc86d0_0  
ncurses                   6.0                  hd04f020_2  
networkx                  1.11             py27h0a72f81_0  
nictools                  1.1.3                    py27_1    http://ssb.stsci.edu/astroconda
nose                      1.3.7            py27h2ee3cb8_2  
notebook                  5.2.1            py27h2702af4_0  
numba                     0.36.2                    <pip>
numexpr                   2.6.4                     <pip>
numpy                     1.13.3           py27h62f9060_0  
numpy                     1.14.0                    <pip>
numpydoc                  0.7.0            py27h022f19e_0  
oktopus                   0.1.1                     <pip>
olefile                   0.44             py27h73ba740_0  
openssl                   1.0.2o                        0    conda-forge
pandas                    0.17.1                    <pip>
pandas                    0.21.0           py27h860f240_1  
pandoc                    1.19.2.1             ha5e8f32_1  
pandocfilters             1.4.2            py27hed78c4e_1  
parsley                   1.3                      py27_0    http://ssb.stsci.edu/astroconda
partd                     0.3.8            py27h7560dbf_0  
pathlib2                  2.3.0            py27he09da1e_0  
pcre                      8.41                 hfb6ab37_1  
pexpect                   4.2.1            py27hc4e4961_0  
photutils                 0.3.1                    py27_0    http://ssb.stsci.edu/astroconda
pickleshare               0.7.4            py27h37e3d41_0  
pillow                    4.2.1            py27h2cf1d5f_0  
pip                       10.0.1                    <pip>
pip                       9.0.1            py27h1567d89_4  
pkg-config                0.29.2               h4abdbbe_5  
pkgconfig                 1.2.2            py27h5ca0bdf_1  
plotly                    2.1.0            py27hbd39481_0  
plotutils                 0.3.2                     <pip>
prompt_toolkit            1.0.15           py27h4a7b9c2_0  
psutil                    5.4.0            py27h7076ac6_0  
ptyprocess                0.5.2            py27h70f6364_0  
purge_path                1.2.0                    py27_0    http://ssb.stsci.edu/astroconda
py                        1.5.2            py27he6783ac_0  
py-expression-eval        0.3.4                    py27_0    http://ssb.stsci.edu/astroconda
pycparser                 2.18             py27h0d28d88_1  
pyds9                     1.9.0.dev       61_g3761d7a_py27_1    http://ssb.stsci.edu/astroconda
pyfftw                    0.9.2                    py27_2    http://ssb.stsci.edu/astroconda
pygments                  2.2.0            py27h1a556bb_0  
pymultinest               2.6                       <pip>
pyobjc-core               3.1.1                    py27_0    http://ssb.stsci.edu/astroconda
pyobjc-framework-cocoa    3.1.1                    py27_0    http://ssb.stsci.edu/astroconda
pyobjc-framework-quartz   3.1.1                    py27_0    http://ssb.stsci.edu/astroconda
pyopengl                  3.1.1a1             np113py27_0  
pyopenssl                 17.2.0           py27h732fe57_0  
pyparsing                 2.2.0            py27h5bb6aaf_0  
pyqt                      5.6.0            py27hf21fe59_6  
pyqtgraph                 0.10.0                   py27_0    http://ssb.stsci.edu/astroconda
pyraf                     2.1.11                   py27_1    http://ssb.stsci.edu/astroconda
pyraf-all                 1.0                      py27_0    http://ssb.stsci.edu/astroconda
pyraf.kepler              2.6.3                    py27_0    http://ssb.stsci.edu/astroconda
pyregion                  1.1.2                    py27_1    http://ssb.stsci.edu/astroconda
pysocks                   1.6.7            py27h1cff6a6_1  
pysynphot                 0.9.8.7                  py27_0    http://ssb.stsci.edu/astroconda
pytest                    3.2.5            py27hc788ff3_0  
python                    2.7.14              h001abdc_23  
python-dateutil           2.6.1            py27hd56c96b_1  
python.app                2                py27hf2d5e94_7  
pytools                   2016.1                   py27_2    http://ssb.stsci.edu/astroconda
pytz                      2017.3           py27h803c07a_0  
pywavelets                0.5.2            py27hd99e88a_0  
pyyaml                    3.12             py27ha7932d0_1  
pyzmq                     16.0.3           py27h91ccc67_0  
qt                        5.6.2               h9975529_14  
qtconsole                 4.3.1            py27hdc90b4f_0  
qtpy                      1.3.1            py27h39159f8_0  
readline                  7.0                  hc1231fa_4  
reftools                  1.7.4                    py27_0    http://ssb.stsci.edu/astroconda
reproject                 0.4                       <pip>
requests                  2.18.4           py27h9b2b37c_1  
scandir                   1.6              py27h97aa1ee_0  
scikit-image              0.13.1           py27ha753da8_0  
scikit-learn              0.19.1                    <pip>
scipy                     0.17.1                    <pip>
scipy                     1.0.0            py27h793f721_0  
semantic_version          2.6.0                    py27_0  
setuptools                36.5.0           py27h2a45cec_0  
simpledist                0.1.12                    <pip>
simplegeneric             0.8.1            py27h6db5e31_0  
singledispatch            3.4.0.3          py27he22c18d_0  
sip                       4.18.1           py27h6300f65_2  
six                       1.11.0           py27h7252ba3_1  
sklearn                   0.0                       <pip>
snowballstemmer           1.2.1            py27h68ac032_0  
sortedcontainers          1.5.7            py27h322dbbf_0  
specutils                 0.2.2                    py27_1    http://ssb.stsci.edu/astroconda
specviz                   0.4.4                    py27_0    http://ssb.stsci.edu/astroconda
sphinx                    1.6.3            py27h11269f0_0  
sphinxcontrib             1.0              py27hd2ed746_1  
sphinxcontrib-websupport  1.0.1            py27h857890b_1  
sqlite                    3.20.1               h7e4c145_2  
ssl_match_hostname        3.5.0.1          py27h8780752_2  
stginga                   0.2.1                    py27_0    http://ssb.stsci.edu/astroconda
stistools                 1.1                      py27_1    http://ssb.stsci.edu/astroconda
stsci                     3.0.0                    py27_0    http://ssb.stsci.edu/astroconda
stsci-data-analysis       2.0.2                    py27_0    http://ssb.stsci.edu/astroconda
stsci-hst                 3.0.0                    py27_1    http://ssb.stsci.edu/astroconda
stsci.convolve            2.2.1                    py27_0    http://ssb.stsci.edu/astroconda
stsci.distutils           0.3.8                    py27_1    http://ssb.stsci.edu/astroconda
stsci.image               2.2.0                    py27_1    http://ssb.stsci.edu/astroconda
stsci.imagemanip          1.1.2                    py27_1    http://ssb.stsci.edu/astroconda
stsci.imagestats          1.4.1                    py27_1    http://ssb.stsci.edu/astroconda
stsci.ndimage             0.10.1                   py27_1    http://ssb.stsci.edu/astroconda
stsci.numdisplay          1.6.1                    py27_1    http://ssb.stsci.edu/astroconda
stsci.skypac              0.9.8                    py27_0    http://ssb.stsci.edu/astroconda
stsci.sphere              0.2                      py27_2    http://ssb.stsci.edu/astroconda
stsci.sphinxext           1.2.2                    py27_0    http://ssb.stsci.edu/astroconda
stsci.stimage             0.2.1                    py27_1    http://ssb.stsci.edu/astroconda
stsci.tools               3.4.11                   py27_0    http://ssb.stsci.edu/astroconda
stwcs                     1.3.2                    py27_0    http://ssb.stsci.edu/astroconda
subprocess32              3.2.7            py27h24b2887_0  
tables                    3.4.2                     <pip>
tblib                     1.3.2            py27ha684fc4_0  
terminado                 0.6              py27he40bf16_0  
testpath                  0.3.1            py27h72d81a5_0  
tk                        8.6.7                h35a86e2_3  
toolz                     0.8.2            py27h27228c4_0  
tornado                   4.5.2            py27h29aec9e_0  
tqdm                      4.19.5                    <pip>
traitlets                 4.3.2            py27hcf08151_0  
triangle-plot             0.3.0                     <pip>
typing                    3.6.2            py27h646fea0_0  
urllib3                   1.22             py27hc3787e9_0  
VESPA                     0.4.10                    <pip>
wcstools                  3.9.5                         0    http://ssb.stsci.edu/astroconda
wcwidth                   0.1.7            py27h817c265_0  
webencodings              0.5.1            py27h19a9f58_1  
wfc3tools                 1.3.4                    py27_1    http://ssb.stsci.edu/astroconda
wfpc2tools                1.0.3                    py27_1    http://ssb.stsci.edu/astroconda
wheel                     0.30.0           py27h677a027_1  
xlrd                      1.1.0            py27hbd41ed1_1  
xz                        5.2.3                h0278029_2  
yaml                      0.1.7                hc338f04_2  
zeromq                    4.2.2                ha360ad0_2  
zict                      0.1.3            py27h5fff8b1_0  
zlib                      1.2.11               hf3cbc9b_2

**Comment by jamienoss** [comment] 2018-08-29 18:36
I too just encountered this very same problem with the healpix import from reproject. I have astropy_healpix 0.2 under a pip install, however, what's interesting is that this was working perfectly with astropy-3.0.2 and only just now failed after I bumped it up to 3.0.4.

I wondered if I had messed something up with https://github.com/astropy/astropy-helpers/pull/382, but I can't have as this issue was opened before that PR was merged.

**Comment by astrofrog** [comment] 2018-09-02 14:14
Just FYI I've release v0.2.1 which has re-generated Cython files (which should fix Cython issues - but not OpenMP issues just to be clear)

**Comment by cdeil** [comment] 2018-09-02 18:26
@astrofrog - Thanks!

**Comment by jamienoss** [comment] 2018-09-05 19:04
I think I understand a possible cause here and can reproduce on my machine with just the simple test code:

```c
#include <omp.h>
#include <stdio.h>
int main(void) {
  #pragma omp parallel
  printf("nthreads=%d\\n", omp_get_num_threads());
  return 0;
}
```

It seems to be a gcc version issue. gcc 4.8.5, i.e. that from conda, doesn't use ``_GOMP_parallel`` but instead splits the block into ``_GOMP_parallel_start`` and ``_GOMP_parallel_end``. For this reason ``libgomp`` doesn't even contain the id ``_GOMP_parallel``, it's just not there. Newer versions of gcc (not sure where the fence is, i'm using 7.1.0 so somewhere in between) do use ``_GOMP_parallel`` and thus it exists in the accompanying library. So it looks like the code is being compiled with a newer ver of gcc yet an older ver of the lib is being used.

@shashankdholakia would you mind looking in ``/anaconda/lib`` for ``libgomp*``, please? I don't see ``gcc`` in your above env list so perhaps it's in the root?

@astrofrog I'm unfamiliar with pip, how do things get built, do you build it yourself? Installing ``astropy-healpix`` via pip and looking at ``/anaconda/lib/python3.6/site-packages/astropy_healpix/compiler.cpython-36m-darwin.so`` I see that it was built with ``GCC version 7.1.0``. The conda-forge version gets built with ``Clang version 7.3.0 (clang-703.0.31)`` and ``otool -L /anaconda/lib/python3.6/site-packages/astropy_healpix/core_cython.cpython-36m-darwin.so`` yeilds
```
/anaconda/lib/python3.6/site-packages/astropy_healpix/core_cython.cpython-36m-darwin.so:
/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
 ```
So the conda clang dist. isn't even built with OpenMP support, which is why it works for @shashankdholakia, and the pip version with too new a ver. of gcc to work with the conda ``libgomp``.

What could be done is:

 1) build the pip dist. with the conda dist. of gcc.
 2) either:
  * build the conda dist. with gcc
  * add llvm-openmp to the OSX dep. list. (prob. needs an astropy-helpers update).

**Comment by cdeil** [comment] 2018-09-05 19:10
> What could be done is:
> build the pip dist. with the conda dist. of gcc.
> either:
> build the conda dist. with gcc
> add llvm-openmp to the OSX dep. list. (prob. needs an astropy-helpers update).

Like I said in #97, IMO we should just remove the use of OpenMP and cut a new release. This would resolve this issue and many more similar issues to come in the coming years if we keep using / deploying with OpenMP.

**Comment by jamienoss** [comment] 2018-09-05 19:18
@cdeil you guys are free to do, or not do, as you please 😃 

This is at least clears up the issue, and also lets @shashankdholakia know that they might be using a build with no OpenMP support.

**Comment by jamienoss** [comment] 2018-09-05 19:39
@cdeil You're welcome.

The self-consistency introduced by conda using their own compilers is an advantage, _not_ a disadvantage. It is intended to actually resolve this type of issue. E.g. regarding:
>so there's many different configurations / issues that can appear on different user machines.

The above self-consitency actually _reduces_ the number of configurations (within the conda ecosystem).

However, this obviously fails when you step outside the conda ecosystem, e.g. installing things via pip or building pip distributions not from a conda env. with correct conda dependencies. Perhaps it's also a bit of a user error/awareness issue, i.e. if you're going to use a conda ecosystem, then do only that.

**Comment by jamienoss** [comment] 2018-09-05 19:47
@astrofrog is there a recipe for the pip build? When I install this package it has a requirement for ``astropy`` and ``numpy``, since the build machine obviously has a ``libgomp`` there must also include an installation dependency for it.

**Comment by astrofrog** [comment] 2018-09-05 19:58
There is no pip 'recipe' - the pip package formally depends on just numpy and astropy. OpenMP is used only if already available otherwise.

**Comment by cdeil** [comment] 2018-09-05 20:01
@jamienoss - I think pip only knows about Python package dependencies.

With Google I found https://pypi.org/project/intel-openmp/ . I had never heard of it, looking at https://github.com/search?p=4&q=intel-openmp&type=Repositories there don't seem to be any major packages using it.

As far as I know there is no reliable way to deploy Python packages that use OpenMP via PyPI / pip.

As long as people are compiling from source and know about compilers and OpenMP it's OK, but as soon as binaries are used (either wheels or conda packages), and a mix of conda and pip is used, it becomes a nightmare.

There is the new https://github.com/scikit-build/scikit-build but even there I couldn't even find a mention of OpenMP.

**Comment by jamienoss** [comment] 2018-09-05 20:07
> OpenMP is used only if already available otherwise.

But this is "if already available" on the build machine, _not_ the run time machine. Once built, the "otherwise" disappears.  This is the issue. If the build is going to be linked against a library, an rt dependency is created, it is a bug in the build/distribution infrastructure/ecosystem if this dependency is _not_ persisted.

**Comment by jamienoss** [comment] 2018-09-05 22:09
...or does it do src distributions and the build is local? Might explain the coincidence of my version being built with gcc-7.1.0.

**Comment by jamienoss** [comment] 2018-09-05 22:34
https://pypi.org/project/astropy-healpix/#files

Ok, so that explains quite a bit. Sorry, I assumed that pip distributions are _always_ pre-built binaries - whoops, my bad.

**Comment by jamienoss** [comment] 2018-09-06 00:15
So it's possible that @shashankdholakia issue was identical to mine, that pip built the package with whatever gets returned by ``which gcc`` (in my case this was _not_ conda's gcc but a non-standard GCC install (loc. only added to ``$PATH``). pip then installed the built package within the python path (for me under conda) causing the rt search to start from there thus finding the non-compatible conda libgcc and _not_ the one it was built with.

A soln. (assuming gcc is conda installed)

``CC=$CONDA_PREFIX/bin/gcc pip install astropy-healpix`` (untested)

**Comment by jamienoss** [comment] 2018-09-06 14:58
@cdeil 
>As far as I know there is no reliable way to deploy Python packages that use OpenMP via PyPI / pip.

Now that I understand pip more, the point you make above is in no way specific to OpenMP, it is a hard fact for any package requiring compilation and dynamic linking to rt libraries. For anything C/C++ this includes ``libgcc`` and it's OS variants, there is no need to go beyond this for rationale. Pip seems completely inadequate for distributing (these types of) binaries without the dependency support that conda has. Using src dists and client-side builds makes some sense, however, multiple versions of rt libraries can easily trip it up.

**Comment by cdeil** [comment] 2018-09-06 15:47
What does "rt" stand for, is it "run time"?

Yes, shipping Python package with C extensions via pip / PyPI isn't great in the first place. But in practice it works pretty well for C extensions, but then the number of issues increases when C++ or OpenMP is used because there differences are larger than in `libc`.

**Comment by jamienoss** [comment] 2018-09-06 17:00
>What does "rt" stand for, is it "run time"?

Correct.

**Comment by cdeil** [comment] 2018-10-23 09:50
OpenMP was removed from astropy-healpix in #108 , which will ship via the upcoming v0.3 shortly.
@shashankdholakia - This will resolve the pip install issue you reported here.

**Closed by cdeil** 2018-10-23 09:50 UTC
Labels: question

**Comment by jamienoss** [comment] 2018-10-23 13:18
@shashankdholakia 
>OpenMP was removed from astropy-healpix in #108 , which will ship via the upcoming v0.3 shortly.
@shashankdholakia - This will resolve the pip install issue you reported here.

Regarding the above comment, #108 only resolves your symptom and not your problem. Just to reiterate your issue was duplicate runtime libraries. You should check this out as it may be causing you other issues for other packages and builds etc.

**Comment by cdeil** [comment] 2018-10-23 14:02
> Regarding the above comment, #108 only resolves your symptom and not your problem. Just to reiterate your issue was duplicate runtime libraries. 

The error reported was an OpenMP-linker error:
```
Symbol not found: _GOMP_parallel
```

Removing the dependency on OpenMP for this package should fully resolve this issue, no?

> You should check this out as it may be causing you other issues for other packages and builds etc.

I don't understand. What other issue do you mean? What else can we as package maintainers do to remove or reduce possible future install issues?

Yes, some users will still pip & conda install binaries that were build using various compilers. Luckily, this usually works for C code as we have it now (but often doesn't for C++ or OpenMP).

**Comment by jamienoss** [comment] 2018-10-23 14:52
>Removing the dependency on OpenMP for this package should fully resolve this issue, no?

It fully resolves the symptom presented by astropy-healpix, not the cause, aka the real issue. I was just trying to tell the issuer that their problem (not astropy-healpix's) is duplicate runtime libraries, in this case, libomp, but may not be exclusive to. There may be other issues without obvious symptoms, i.e. API conflicts, and this may also be present in other packages that they are trying to build and install.

Basically, your solution is analogous to stating a cure for the common cold being never to expose yourself to rhinoviruses.

>What else can we as package maintainers do to remove or reduce possible future install issues?

Before you ask _how_ can we do something, you should first ask _should_ we do something. Responsibility should be questioned. This specific issue is an environment conflict issue, it is one that is general and thus not specific to this package, even though it was reported for this package. Because of this, it is not the responsibility of the package maintainers to prevent such an issue, because it is not their responsibility to do so, largely (in this case), because they cannot. I know of no package that would run a sweep of the environment checking for conflicts, not even package managers like apt-get (I think), conda, and obviously, pip, do this.

The only real solution to solving this issue is to not distribute the src via pypi.

**Comment by cdeil** [comment] 2018-10-23 15:03
Ah, OK, then I understand your previous comment now.

> The only real solution to solving this issue is to not distribute the src via pypi.

I think it's clear that this is not an option we are pursuing. Instead the opposite: try to make install just work for distribution via PyPI and any other distribution channel as best we can.

**Comment by jamienoss** [comment] 2018-10-23 15:21
>>The only real solution to solving this issue is to not distribute the src via pypi.
>I think it's clear that this is not an option we are pursuing. 

Crystal. Which then leaves the only alternative which is to do nothing. Though maybe user awareness is needed, however, this would be very generic advice related to conda & pip rather than any given package.

I feel that users should be free to (attempt) to build the package with whichever build tool-chain they desire. If they choose poorly, they have chosen poorly. Regardless of whether OpenMP support is incorporated into the package, or not, this issue (an API conflict due to duplicate rt libs) is present for any and all other non-python dependencies. The only thing that could be done is try to constrain this via build recipes, my understanding is that this is not possible within the pip ecosystem.

**Comment by cdeil** [comment] 2018-10-23 15:44
> I feel that users should be free to (attempt) to build the package with whichever build tool-chain they desire. If they choose poorly, they have chosen poorly. 

I feel differently. Most users are astronomers. They shouldn't have to care about compilers and linkers. As much as possible, we should aim to make a package where install just works everywhere.

> Regardless of whether OpenMP support is incorporated into the package, or not, this issue (an API conflict due to duplicate rt libs) is present for any and all other non-python dependencies.

In my experience, there is a big distinction in portability between `libc` on the one hand, and OpenMP and C++ on the other. For Python projects I worked on that used just C, things worked fine. For all Python projects I helped maintain that used C++ and / or OpenMP, some linker issue reports from users came. So it's a tradeoff one has to make between performance, and ease of installation / distribution.

> The only thing that could be done is try to constrain this via build recipes, my understanding is that this is not possible within the pip ecosystem.

Agreed. There's nothing further we can / should do here.

**Comment by jamienoss** [comment] 2018-10-23 16:07
>Most users are astronomers. They shouldn't have to care about compilers and linkers.

I totally agree, they should not. It's why I feel that pip isn't the right tool for the job as it has no functionality to allow the maintaners to aliviate the users/installers of these issues by doing it for them in build recipes etc.

>I feel that users should be free to (attempt) to build the package with whichever build tool-chain they desire. If they choose poorly, they have chosen poorly.

I meant for this to only apply to those that consciously "choose" and not the nominal user.
