### ISSUE TITLE
Release v0.3

### ISSUE THREAD

**Issue by cdeil** [astropy/astropy-healpix#109] opened 2018-10-24 06:06 UTC
@astrofrog @lpsinger - I'll just go ahead and release v0.3 today.

**Comment by cdeil** [comment] 2018-10-24 06:29
Added changelog to docs and updated for v0.3 in 52dfc064ffcb6025cd18b5e343bf9c96d5d1eede and d8ccff3819fd8bb9e31a206edd8182878e19e582

**Comment by cdeil** [comment] 2018-10-24 06:54
In master there's a few broken CI builds, due to two matplotlib issues:

The first one seems to be a MPL issue:
```
ImportError: cannot import name 'get_backend'
```
https://travis-ci.org/astropy/astropy-healpix/jobs/445499165#L1127
I've commented here: https://github.com/matplotlib/matplotlib/issues/12610#issuecomment-432532909

The seconds is:
```
INTERNALERROR> AttributeError: module 'matplotlib' has no attribute 'artist'
```
https://travis-ci.org/astropy/astropy-healpix/jobs/445499168#L1159
I'm not sure if it's related to the first one or not, the traceback also mentions MPL rcParams, as well as astropy/utils/introspection.py .

@astrofrog - Is there anything to do here (an edit in `astropy/utils/introspection.py` or send an issue or comment to MPL?

I'll just go ahead with the astropy-healpix v0.3 release, this looks like MPL issues to me and there's no edits in astropy-healpix to make.

**Comment by cdeil** [comment] 2018-10-24 07:10
Another issue I noticed is that the docs build for a released package doesn't work.

To reproduce:
```
python setup.py sdist
cd dist
tar zxvf astropy-healpix-0.3.tar.gz
cd astropy-healpix-0.3
python setup.py build docs
```

gives this error:
```
jinja2.exceptions.TemplateNotFound: autosummary_core/base.rst
```
https://gist.github.com/cdeil/ceb592b5002a025d7897704d05ecc01c

Again, I'll just go ahead and do the release now. Tests pass locally for the package from the sdist. Not sure if building the docs from the sdist is even supposed to work. @astrofrog - Just wanted to mention it in case it's a bug.

**Comment by cdeil** [comment] 2018-10-24 07:18
Release is done:
- https://github.com/astropy/astropy-healpix/releases/tag/v0.3
- https://pypi.org/project/astropy-healpix/0.3/

@lpsinger @astrofrog - Please try to install and run tests, and see if everything works for you.

I think some bot should pick up the release and make a PR for https://github.com/conda-forge/astropy-healpix-feedstock within the next day. Keeping this issue open until conda-forge is done.

**Comment by cdeil** [comment] 2018-10-24 07:28
RTD is also OK: https://astropy-healpix.readthedocs.io/en/v0.3/changes.html

So the only missing thing is the conda-forge builds. v0.3 should appear here:
https://anaconda.org/conda-forge/astropy-healpix

I'll check again tomorrow for status there.

**Comment by cdeil** [comment] 2018-10-24 07:38
@astrofrog - Please have a look:
https://travis-ci.org/conda-forge/astropy-healpix-feedstock/jobs/445513657#L584

**Comment by astrofrog** [comment] 2018-10-24 07:47
@cdeil - I think you forgot to add 'build' in the sdist command, it should be:

```
python setup.py build sdist
```

**Comment by astrofrog** [comment] 2018-10-24 07:49
Basically that adds the C files - otherwise Cython is required for the installation.

**Comment by astrofrog** [comment] 2018-10-24 07:51
There are two options at this point:

- Run ``python setup.py build sdist`` on the ``v0.3`` tagged version and then rename the tar file so that the filename has version ``v0.3.post1`` in the name

- Make a v0.3.x branch from the v0.3 tag, and update the version to v0.3.1 the re-release

**Comment by astrofrog** [comment] 2018-10-24 07:53
Btw I can investigate the MPL and docs issue later today, I agree it doesn't need to hold up the release

**Comment by cdeil** [comment] 2018-10-24 07:55
I see. Yes, I ran `python setup.py build sdist` and the C files are missing from the sdist.

Which of the two options you mentioned would you recommend?
Do you want to do it or should I?

**Comment by astrofrog** [comment] 2018-10-24 08:19
@cdeil - I think the first is sufficient since it is purely a packaging issue. I'm happy to do it now.

**Comment by cdeil** [comment] 2018-10-24 08:20
@astrofrog - Thank you!

And apologies for the mistake and extra hassle!

**Comment by astrofrog** [comment] 2018-10-24 08:34
@cdeil - no worries, I've done this myself before! I wonder if it would make sense to just patch sdist to do it automatically in astropy-helpers?

In the end I released v0.3.1, because I got scared by the post1 approach (see e.g. https://github.com/astropy/astropy/issues/4406)

**Comment by cdeil** [comment] 2018-10-24 08:44
Thanks! Just keeping it simple and using "Z" in "vX.Y.Z" for bugfix releases makes sense to me.

FYI: there were about 10 old merged feature branches in the main repo, most from me. I deleted those, just keeping the branches that should be in the shared repo just now:
https://github.com/astropy/astropy-healpix/branches

**Comment by astrofrog** [comment] 2018-10-24 09:46
Sounds good about the branches. I'll close this since v0.3.1 is out and the conda build seems to be working.

**Closed by astrofrog** 2018-10-24 09:46 UTC
Labels: enhancement

**Comment by cdeil** [comment] 2018-10-24 09:58
I see packages are already at https://anaconda.org/conda-forge/astropy-healpix/files

Works for me on macOS:
```
conda install -c conda-forge astropy-healpix
python -c 'import astropy_healpix; astropy_healpix.test()'
```

@astrofrog - Thanks!

**Comment by lpsinger** [comment] 2018-10-25 13:13
I can confirm that #106 is fixed in the latest release. Thanks!
